### PR TITLE
Bump to 1.29.0

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Not sure why this packages an old version, so here is a bump that worked locally, but it seems like cabal downloaded some requirements... The goal of this bump is mostly to get the `json-to-dhall` cli.

**Comment by juhp** [comment]
Ah, thank you - because cabal-rpm currently defaults to lts13 doh
(will fix that too for standalone packages)...

**Comment by juhp** [comment]
I updated the deps in 695dcd8 and added dhall-yaml too.

**Comment by juhp** [comment]
I am updating my copr

**Pull request merged**
